# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75729479670961630f555b7a5e5c4f74950991deeb0ddfc0aa67575d14f3302bb78e96caeae253c6fab1c99d6e041bac455424f2baec38be9ed4277f1f483eb6

test:
  secret_key_base: 315090ccbf832656897537b39a63c3a9bcb038701e08e24ce0cdaaab1ccc8f8a82386c2a281b2d785c70fc04d08e378c04a4467656fc3feda3525513d0f84086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
